<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.


/**
 * Defines class for course appointments block
 *
 * @package block
 * @subpackage course_appointments
 * @author      Mark Johnson <mark.johnson@tauntons.ac.uk>
 * @copyright   2010 Tauntons College, UK
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

@require_once($CFG->libdir.'/sms/smslib.php');
require_once($CFG->libdir.'/bennu/bennu.class.php');
/**
 *  Course Appointments block class
 *
 *  Extends standard block methods, and defines methods for display,
 *  validation and processing of the form.
 *
 */
class block_course_appointments extends block_base {

    /**
     * Stores the student record during validation and processing
     *
     * @var object
     */
    var $student;
    /**
     * Stores the event start timestamp during validation and processing
     *
     * @var object
     */
    var $timestamp;

    /**
     * Standard block init method, defines the title
     */
    function init() {
        $this->title = get_string('pluginname', 'block_course_appointments');
    }

    /**
     * Restricts block to course pages
     *
     * @see blocks/block_base#applicable_formats()
     * @return array
     */
    function applicable_formats() {
        return array('course-view' => true,
                'all' => false);
    }
    /**
     * Prevent multiple instances of the block on a page
     * @return boolean
     */
    function allow_multiple() {
        return false;
    }
     
    /**
     * Cron job, sends reminder texts once a day
     *
     * Runs every hour with block's cron job, but only does anything between 8am and 9am (so
     * once a day).  Looks for any appoinments happening today, and if there's a valid mobile
     * number for the student, sends them a reminder via SMS.
     */
    function cron() {
        global $DB;
        if (date('H') == '08') { // If it's between 8 and 9 AM
            $params = array("%S%", strtotime('today'), strtotime('tomorrow'));
            $appointments = $DB->get_records_select('event', 'uuid LIKE ? AND timestart BETWEEN ? AND ?', $params);
            foreach ($appointments as $appointment) {
                $student = get_record('user', 'id', $appointment->userid);
                $teacher_appointment = get_record('event', 'uuid = '.str_replace('S', 'T', $appointment->uuid));
                $teacher = get_record('user', 'id', $teacher_appointment->userid);
                $a = new stdClass;
                $a->name = fullname($teacher);
                $a->time = date('H:i', $appointment->timestart);
                $sms = SMS::Loader($CFG);
                if ($sms->format_number($student->phone2)) {
                    $sent = $sms->send_message(array($student->phone2), get_string('remindsms', 'block_course_appointments', $a));
                }
            }
        }
    }

    /**
     * Displays the block containing an appointment form
     *
     * Checks that the user has permission to use the block, and if they do, displays the
     * booking form generated by {@see build_form()}
     * Also loads the block's javascript module for displaying the calendar selector.
     *
     * @see blocks/block_base#get_content()
     */
    function get_content() {
        global $CFG, $COURSE, $SESSION, $DB;
        if ($this->content !== NULL) {
            return $this->content;
        }
        $this->content->text = '';
        $coursecontext = get_context_instance(CONTEXT_COURSE, $COURSE->id);
        if (has_capability('block/course_appointments:book', $coursecontext)) {
            if (isset($SESSION->course_appointments['errors'])) {
                $this->display_errors($SESSION->course_appointments['errors']);
            }

            $this->content->text .= $this->build_form($coursecontext);
            unset($SESSION->course_appointments);
        }

        $this->content->footer = '';
        $jsmodule = array(
            'name'  =>  'block_course_appointments',
            'fullpath'  =>  '/blocks/course_appointments/module.js',
            'requires'  =>  array('base', 'node')
        );

        $this->page->requires->js_init_call('M.block_course_appointments.init', array(), false, $jsmodule);
        return $this->content;
    }

    /**
     * Generates the HTML for the appointment booking form.
     *
     * Gets a list of students enrolled on the course.  Then generates the HTML for a select
     * list containing students, a date field with a button to launch a calendar selector,
     * select lists for the appointment time, and an option to notify the student by SMS.
     *
     * @param $coursecontext Context object for the course we can get current users.
     * @return string HTML for the form.
     */
    function build_form($coursecontext) {
        global $CFG, $COURSE, $SESSION, $DB, $OUTPUT;
        $studentrole = $DB->get_record('role', array('shortname' => 'student'));
        $studentassignments = get_users_from_role_on_context($studentrole, $coursecontext);
        $url = new moodle_url('/blocks/course_appointments/process.php');
        $studentlist = array();

        foreach($studentassignments as $studentassignment) {
            $studentrecord = $DB->get_record('user', array('id' => $studentassignment->userid));
            $studentlist[$studentrecord->id] = fullname($studentrecord);
        }

        $hours = range(0, 23);
        $minutes = range(0, 59);
        foreach (array('hours', 'minutes') as $array) {
            foreach (${$array} as $k => $v) {
                ${$array}[$k] = str_pad($v, 2, '0', STR_PAD_LEFT);
            }
        }
        $selected_student = null;
        $selected_date = null;
        $selected_time = array('hours' => '', 'minutes' => '');
        $checked = '';

        if (isset($SESSION->course_appointments['appointment_student'])) {
            $selected_student = $SESSION->course_appointments['appointment_student'];
        }
        if (isset($SESSION->course_appointments['appointment_date'])) {
            $selected_date = $SESSION->course_appointments['appointment_date'];
        } else {
            $selected_date = date('d M Y');
        }
        if (isset($SESSION->course_appointments['appointment_time_hours'])) {
            $selected_time['hours'] = $SESSION->course_appointments['appointment_time_hours'];
        } else {
            $selected_time['hours'] = date('H');
        }
        if (isset($SESSION->course_appointments['appointment_time_minutes'])) {
            $selected_time['minutes'] = $SESSION->course_appointments['appointment_time_minutes'];
        } else {
            $selected_time['minutes'] = date('i');
        }
        if (isset($SESSION->course_appointments['appointment_notify']) && $SESSION->course_appointments['appointment_notify'] == 1) {
            $checked = 'checked';
        }

        $form = html_writer::start_tag('form', array('id' => "block_courseappointments_form", 'action' => $url, 'method' => "post"));
        $form .= html_writer::empty_tag('input', array('type' => "hidden", 'name' => "courseid", 'value' => $COURSE->id));
        $form .= html_writer::start_tag('div', array('class' => "formrow"));
        $form .= html_writer::tag('label', $studentrole->name, array('for' => "appointment_student"));
        $form .= html_writer::select($studentlist, 'appointment_student', $selected_student);
        $form .= html_writer::end_tag('div');

        $form .= html_writer::start_tag('div', array('class' => "formrow", 'id' => "block_courseappointments_daterow"));
        $form .= html_writer::tag('label', get_string('date'), array('for' => "date"));
        $form .= html_writer::empty_tag('input', array('type' => "text", 'id' => "block_courseappointments_appointmentdate", 'name' => "appointment_date", 'value' => $selected_date));
        $form .= html_writer::start_tag('button', array('type' => "button", 'id' => "block_courseappointments_show", 'title' => "Show Calendar"));
        $form .= html_writer::empty_tag('img', array('src' => $OUTPUT->pix_url('i/calendar'), 'alt' => "Calendar"));
        $form .= html_writer::end_tag('button');
        $form .= html_writer::end_tag('div');

        $form .= html_writer::tag('div', '', array('id' => "block_courseappointments_calendarcontainer"));

        $form .= html_writer::start_tag('div', array('class' => "formrow"));
        $form .= html_writer::tag('label', get_string('time'), array('for' => "appointment_time_hours"));
        $form .= html_writer::select($hours, 'appointment_time_hours', $selected_time['hours'], array());
        $form .= ':';
       	$form .= html_writer::select($minutes, 'appointment_time_minutes', $selected_time['minutes'], array());
       	$form .= html_writer::end_tag('div');

        $form .= html_writer::start_tag('div', array('class' => "formrow"));
        $form .= html_writer::tag('label', get_string('notifystudent', 'block_course_appointments'), array('for' => "appointment_notify"));
        $form .= html_writer::empty_tag('input', array('type' => "hidden", 'name' => "appointment_notify", 'value' => "0"));
        $form .= html_writer::empty_tag('input', array('type' => "checkbox", 'name' => "appointment_notify", 'value' => "1", 'checked' => $checked));
        $form .= html_writer::end_tag('div');

        $form .= html_writer::empty_tag('input', array('type' => "submit", 'name' => "appointment_submit", 'value' => get_string('book', 'block_course_appointments')));
        $form .= html_writer::end_tag('form');
        return $form;
    }
    
    /**
     * Reads in POSTed data from the form, validates it and stores it for processing
     * 
     * Reads studentid, date and time from the form, checks that the student exists,
     * converst the date and time to unix time, and checks that it's valid and not in the past.
     * Returns an error message for each error encountered, or false otherwise.
     * Validated data is stored in {@see $student} and {@see $timestamp} for
     * easy access by {@see process_form()}.
     * Raw data is stored in the user's session in case it needs redisplaying on the form.
     * 
     * @return array|bool	Array of error messages, or false if none.
     */
    function validate_form() {
        global $SESSION, $DB;
        $studentid = optional_param('appointment_student', 0, PARAM_INT);
        $SESSION->course_appointments['appointment_student'] = $studentid;
        $datestring = optional_param('appointment_date', 0, PARAM_TEXT);
        $SESSION->course_appointments['appointment_date'] = $datestring;
        $hours = optional_param('appointment_time_hours', 0, PARAM_TEXT);
        $SESSION->course_appointments['appointment_time_hours'] = $hours;
        $mins = optional_param('appointment_time_minutes', 0, PARAM_TEXT);
        $SESSION->course_appointments['appointment_time_mins'] = $mins;
        $this->timestamp = strtotime($datestring.' '.$hours.':'.$mins);
        $errors = array();

        if (empty($studentid)) {
            $errors[] = get_string('nostudent', 'block_course_appointments');
        } else {
            if(!$this->student = $DB->get_record('user', array('id' => $studentid))) {
                $errors[] = get_string('studentdoesntexist', 'block_course_appointments');
            }
        }

        if (empty($datestring)) {
            $errors[] = get_string('nodate', 'block_course_appointments');
        }

        if (empty($this->timestamp) || $this->timestamp == -1) {
            $errors[] = get_string('invaliddate', 'block_course_appointments');
        } else if ($this->timestamp < time()) {
            $errors[] = get_string('pastdate', 'block_course_appointments');
        }

        if (empty($errors)) {
            return false;
        } else {
            return $errors;
        }
    }
    
    /**
     * Processes the validated data and inserts appointments into the database.
     * 
     * Takes the validated student record and appointment timestamp from the object's properties.
     * Generates an unique UUID, and edits it so it can be used to identify the two appointmetns
     * as linked, and inserts a user event into the database for both the student and the teacher
     * (current user).  Then clears the session data for the block so the data isn't redisplayed
     * in the form.	
     * If the notify checkbox was ticked, an email and SMS wil also be sent to the student.
     * 
     */
    function process_form() {
        global $USER, $COURSE, $CFG, $SESSION, $DB;
        global $sms;
        $notify = optional_param('appointment_notify', 0, PARAM_INT);
        $names = new stdClass;
        $names->student = fullname($this->student);
        $names->teacher = fullname($USER);
        $uuid = Bennu::generate_guid();
        $appointment = new stdClass;
        $appointment->name = get_string('entryname', 'block_course_appointments', $names->student);
        $appointment->description = get_string('entrydescription', 'block_course_appointments', $names);
        $appointment->userid = $USER->id;
        $appointment->timestart = $this->timestamp;

        // To identify the two appointments as linked, we use the same UUID for both, but replace the
        // dashes with T (for Teacher) and S (For student). Since neither character is Hexadecimal, they
        // wont occur in any generated UUID.
        $appointment->uuid = str_replace('-', 'T', $uuid);
        $appointment->format = 1;
        $DB->insert_record('event', $appointment);
        $appointment->name = get_string('entryname', 'block_course_appointments', $names->teacher);
        $appointment->userid = $this->student->id;
        $appointment->uuid = str_replace('-', 'S', $uuid);
        $DB->insert_record('event', $appointment);
        $names->date = date('d/m/Y', $this->timestamp);
        $names->time = date('H:i', $this->timestamp);
        $notified = false;
        if ($notify) {
            $notified = email_to_user($this->student, $USER, get_string('notifysubject', 'block_course_appointments', $names->teacher), get_string('notifytext', 'block_course_appointments', $names));
            $sms = SMS::Loader($CFG);
            if ($sms->format_number($this->student->phone2)) {
                $sent = $sms->send_message(array($this->student->phone2), get_string('notifysms', 'block_course_appointments', $names));
                foreach($sent->responses as $response) { // Create a list of users to whom the message failed to send
                    if($response->code == 1) {
                        $notified = true;
                    }
                }
            }
        }
        $SESSION->course_appointments = array();
        if ($notify && !$notified) {
            $SESSION->course_appointments['errors'][] = get_string('notnotified', 'block_course_appointments');
        }
    }

    /**
     * Formats the error messages as HTML.
     * 
     * @param $errors error messages generated by {@see validate_form()}
     */
    function display_errors($errors) {
        $this->content->text .= html_writer::start_tag('div', array('class' => "errors"));
        foreach ($errors as $error) {
            $this->content->text .= $error.html_writer::empty_tag('br');
        }
        $this->content->text .= html_writer::end_tag('div');
    }
}
?>
